client:
  token: 0
  applicationId: 0
  
imperial:
  use_api_key: false
  api_key: 0
  use_har: true
  har_path: /path/to/har/file.har

database:
  host: 127.0.0.1
  port: 3306
  username: username
  password: password
  name: name
  merchant_suffix: _merchant_settings

dev:
  debug: true